/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is automatically generated by Next.js
// Do not modify it manually - changes may be overwritten

// Add custom type definitions for environment variables
declare namespace NodeJS {
  interface ProcessEnv {
    // Firebase configuration
    NEXT_PUBLIC_FIREBASE_API_KEY: string;
    NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: string;
    NEXT_PUBLIC_FIREBASE_PROJECT_ID: string;
    NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: string;
    NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: string;
    NEXT_PUBLIC_FIREBASE_APP_ID: string;

    // API endpoints
    NEXT_PUBLIC_WEBSOCKET_URL: string;
    NEXT_PUBLIC_API_URL: string;

    // External service keys
    NEXT_PUBLIC_OPENAI_API_KEY: string;
    NEXT_PUBLIC_GOOGLE_CLIENT_ID: string;
  }
}

// Ensure Next.js types are properly extended
interface CSSModule {
  [className: string]: string;
}

declare module '*.module.css' {
  const classes: CSSModule;
  export default classes;
}

declare module '*.module.scss' {
  const classes: CSSModule;
  export default classes;
}